# Generated by Django 3.0.4 on 2020-10-06 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Nome do curso *')),
                ('area', models.CharField(choices=[('CIÊNCIAS DA SAÚDE', 'Ciências da Saúde'), ('CIÊNCIAS HUMANAS', 'Ciências Humanas'), ('CIÊNCIAS SOCIAIS', 'Ciências Sociais'), ('CIÊNCIAS TECNOLÓGICAS', 'Ciências Tecnológicas')], max_length=25, verbose_name='Área de conhecimento do curso *')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Email do curso')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador *')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
    ]
