# Generated by Django 3.1.5 on 2021-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('usuario', '0004_auto_20201027_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.ManyToManyField(blank=True, help_text='Para selecionar ou não um curso, use o mouse e a tecla CTRL', null=True, to='curso.Curso', verbose_name='Curso'),
        ),
    ]
