# Generated by Django 3.0.4 on 2020-09-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='* Campos obrigatórios', max_length=20, unique=True, verbose_name='Código da ata *')),
                ('data', models.DateField(help_text='dd/mm/aaaa', max_length=11, verbose_name='Data da reunião *')),
                ('hora', models.CharField(help_text='hh:mm', max_length=5, verbose_name='Hora da reunião *')),
                ('local', models.CharField(max_length=50, verbose_name='Local da reunião *')),
                ('pauta', models.TextField(max_length=200, verbose_name='Pauta da reunião *')),
                ('texto', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Texto da reunião *')),
                ('validada', models.BooleanField(blank=True, null=True, verbose_name='Ata validada? ')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('integrantes', models.ManyToManyField(blank=True, null=True, related_name='integrantes', to=settings.AUTH_USER_MODEL, verbose_name='Integrantes')),
                ('redator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redator', to=settings.AUTH_USER_MODEL, verbose_name='Redator *')),
            ],
            options={
                'verbose_name': 'ata',
                'verbose_name_plural': 'atas',
                'ordering': ['codigo', '-data', '-hora'],
                'unique_together': {('codigo', 'data', 'hora')},
            },
        ),
    ]
