# Generated by Django 3.0.4 on 2020-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='arquivo_anexo1',
            field=models.FileField(blank=True, help_text='Se houver mais de um arquivo, sugere-se enviar o compactado', null=True, upload_to='midias', verbose_name='Anexo à reunião'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='pauta',
            field=models.TextField(max_length=200, verbose_name='Pauta da reunião'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='texto',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Texto da reunião'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='validada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ata validada? '),
        ),
    ]
