# Generated by Django 3.0.4 on 2020-10-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('atas', '0002_auto_20201020_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='curso', to='curso.Curso', verbose_name='Curso *'),
            preserve_default=False,
        ),
    ]
